 version: '3.7'

 services:
  server:
    image: nginx
    env_file:
      - .env
    container_name: 'SERVER-WEB-${MODE}'
    ports:
      - 9090:80
    volumes:
      - ./src:/usr/share/nginx/html
    command: [nginx-debug, '-g', 'daemon off;']

    
  